import subprocess
import shutil
def main():
	correspond_job_dir = '/home/heinhtet/Desktop/UPC_APLAS/'
	clear_jobs(correspond_job_dir)

def clear_jobs(directory):
	subprocess.call(['rm', '-r', directory+'PC1'])
	subprocess.call(['rm', '-r', directory+'PC2'])
	subprocess.call(['rm', '-r', directory+'PC3'])
	subprocess.call(['rm', '-r', directory+'PC4'])
	subprocess.call(['rm', '-r', directory+'PC5'])
	subprocess.call(['rm', '-r', directory+'PC6'])
	subprocess.call(['rm', '-r', directory+'PC1_c'])
	subprocess.call(['rm', '-r', directory+'PC2_c'])
	subprocess.call(['rm', '-r', directory+'PC3_c'])
	subprocess.call(['rm', '-r', directory+'PC4_c'])
	subprocess.call(['rm', '-r', directory+'PC5_c'])
	subprocess.call(['rm', '-r', directory+'PC6_c'])
	subprocess.call(['rm', '-r', directory+'worker-1'])
	subprocess.call(['rm', '-r', directory+'worker-2'])
	subprocess.call(['rm', '-r', directory+'worker-3'])
	subprocess.call(['rm', '-r', directory+'worker-4'])
	subprocess.call(['rm', '-r', directory+'worker-5'])
	subprocess.call(['rm', '-r', directory+'worker-6'])
	subprocess.call(['rm', '-r', directory+'c_PC1'])
	subprocess.call(['rm', '-r', directory+'c_PC2'])
	subprocess.call(['rm', '-r', directory+'c_PC3'])
	subprocess.call(['rm', '-r', directory+'c_PC4'])
	subprocess.call(['rm', '-r', directory+'c_PC5'])
	subprocess.call(['rm', '-r', directory+'c_PC6'])
	subprocess.call(['rm', '-r', directory+'PC1_c_result'])
	subprocess.call(['rm', '-r', directory+'PC2_c_result'])
	subprocess.call(['rm', '-r', directory+'PC3_c_result'])
	subprocess.call(['rm', '-r', directory+'PC4_c_result'])
	subprocess.call(['rm', '-r', directory+'PC5_c_result'])
	subprocess.call(['rm', '-r', directory+'PC6_c_result'])
	subprocess.call(['rm', '-r', directory+'PC11'])
	subprocess.call(['rm', '-r', directory+'PC22'])
	subprocess.call(['rm', '-r', directory+'PC33'])
	subprocess.call(['rm', '-r', directory+'PC44'])
	subprocess.call(['rm', '-r', directory+'PC55'])
	subprocess.call(['rm', '-r', directory+'PC66'])
	create(directory)

def create(directory):
	subprocess.call(['mkdir', directory+'PC1'])
	subprocess.call(['chmod', '777', '-R', directory+'PC1'])
	subprocess.call(['mkdir', directory+'PC2'])
	subprocess.call(['chmod', '777', '-R', directory+'PC2'])
	subprocess.call(['mkdir', directory+'PC3'])
	subprocess.call(['chmod', '777', '-R', directory+'PC3'])
	subprocess.call(['mkdir', directory+'PC4'])
	subprocess.call(['chmod', '777', '-R', directory+'PC4'])
	subprocess.call(['mkdir', directory+'PC5'])
	subprocess.call(['chmod', '777', '-R', directory+'PC5'])
	subprocess.call(['mkdir', directory+'PC6'])
	subprocess.call(['chmod', '777', '-R', directory+'PC6'])
	subprocess.call(['mkdir', directory+'PC1_c'])
	subprocess.call(['chmod', '777', '-R', directory+'PC1_c'])
	subprocess.call(['mkdir', directory+'PC2_c'])
	subprocess.call(['chmod', '777', '-R', directory+'PC2_c'])
	subprocess.call(['mkdir', directory+'PC3_c'])
	subprocess.call(['chmod', '777', '-R', directory+'PC3_c'])
	subprocess.call(['mkdir', directory+'PC4_c'])
	subprocess.call(['chmod', '777', '-R', directory+'PC4_c'])
	subprocess.call(['mkdir', directory+'PC5_c'])
	subprocess.call(['chmod', '777', '-R', directory+'PC5_c'])
	subprocess.call(['mkdir', directory+'PC6_c'])
	subprocess.call(['chmod', '777', '-R', directory+'PC6_c'])
	subprocess.call(['mkdir', directory+'worker-1'])
	subprocess.call(['chmod', '777', '-R', directory+'worker-1'])
	subprocess.call(['mkdir', directory+'worker-2'])
	subprocess.call(['chmod', '777', '-R', directory+'worker-2'])
	subprocess.call(['mkdir', directory+'worker-3'])
	subprocess.call(['chmod', '777', '-R', directory+'worker-3'])
	subprocess.call(['mkdir', directory+'worker-4'])
	subprocess.call(['chmod', '777', '-R', directory+'worker-4'])
	subprocess.call(['mkdir', directory+'worker-5'])
	subprocess.call(['chmod', '777', '-R', directory+'worker-5'])
	subprocess.call(['mkdir', directory+'worker-6'])
	subprocess.call(['chmod', '777', '-R', directory+'worker-6'])
	subprocess.call(['mkdir', directory+'c_PC1'])
	subprocess.call(['chmod', '777', '-R', directory+'c_PC1'])
	subprocess.call(['mkdir', directory+'c_PC2'])
	subprocess.call(['chmod', '777', '-R', directory+'c_PC2'])
	subprocess.call(['mkdir', directory+'c_PC3'])
	subprocess.call(['chmod', '777', '-R', directory+'c_PC3'])
	subprocess.call(['mkdir', directory+'c_PC4'])
	subprocess.call(['chmod', '777', '-R', directory+'c_PC4'])
	subprocess.call(['mkdir', directory+'c_PC5'])
	subprocess.call(['chmod', '777', '-R', directory+'c_PC5'])
	subprocess.call(['mkdir', directory+'c_PC6'])
	subprocess.call(['chmod', '777', '-R', directory+'c_PC6'])
	subprocess.call(['mkdir', directory+'PC1_c_result'])
	subprocess.call(['chmod', '777', '-R', directory+'PC1_c_result'])
	subprocess.call(['mkdir', directory+'PC2_c_result'])
	subprocess.call(['chmod', '777', '-R', directory+'PC2_c_result'])
	subprocess.call(['mkdir', directory+'PC3_c_result'])
	subprocess.call(['chmod', '777', '-R', directory+'PC3_c_result'])
	subprocess.call(['mkdir', directory+'PC4_c_result'])
	subprocess.call(['chmod', '777', '-R', directory+'PC4_c_result'])
	subprocess.call(['mkdir', directory+'PC5_c_result'])
	subprocess.call(['chmod', '777', '-R', directory+'PC5_c_result'])
	subprocess.call(['mkdir', directory+'PC6_c_result'])
	subprocess.call(['chmod', '777', '-R', directory+'PC6_c_result'])
	subprocess.call(['mkdir', directory+'PC11'])
	subprocess.call(['chmod', '777', '-R', directory+'PC11'])
	subprocess.call(['mkdir', directory+'PC22'])
	subprocess.call(['chmod', '777', '-R', directory+'PC22'])
	subprocess.call(['mkdir', directory+'PC33'])
	subprocess.call(['chmod', '777', '-R', directory+'PC33'])
	subprocess.call(['mkdir', directory+'PC44'])
	subprocess.call(['chmod', '777', '-R', directory+'PC44'])
	subprocess.call(['mkdir', directory+'PC55'])
	subprocess.call(['chmod', '777', '-R', directory+'PC55'])
	subprocess.call(['mkdir', directory+'PC66'])
	subprocess.call(['chmod', '777', '-R', directory+'PC66'])

if __name__=="__main__":
	main()	