#Define the base image
FROM #FROM


#Set the environment variables to run the project
ENV #ENV


#Create project directory and inform Docker to run under this directory
WORKDIR #WORKDIR


#Add commands and parameters(Docker runs this firstly when container runs)
ENTRYPOINT #ENTRYPOINT


#Run commands after ENTRYPOINT run(must have at least one CMD)
CMD #CMD


#Copy one or more files and folders from local to containers file system
COPY #COPY


#Same with COPY but for archive and URL copy and execute
ADD #ADD


#Execute any commands on top of the current image
RUN #RUN


#Inform the Docker that container listens on the specified network ports
EXPOSE #EXPOSE


#Specify the Dockerfile Author Name and Email
MAINTAINER #MAINTAINER
